---
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  annotations:
    app.quarkus.io/vcs-url: "https://github.com/Stywar/Quakus-security.git"
    app.quarkus.io/build-timestamp: "2020-07-23 - 05:39:59 +0000"
    app.quarkus.io/commit-id: "6cb7c92981249384cb76f02a668eebd789fc7bc3"
  labels:
    app.kubernetes.io/name: "aforo255-security"
    app.kubernetes.io/version: "1.0.0-SNAPSHOT"
  name: "aforo255-security"
---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    app.quarkus.io/vcs-url: "https://github.com/Stywar/Quakus-security.git"
    app.quarkus.io/build-timestamp: "2020-07-23 - 05:39:59 +0000"
    app.quarkus.io/commit-id: "6cb7c92981249384cb76f02a668eebd789fc7bc3"
  labels:
    app.kubernetes.io/name: "aforo255-security"
    app.kubernetes.io/version: "1.0.0-SNAPSHOT"
  name: "aforo255-security"
spec:
  ports:
  - name: "http"
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: "aforo255-security"
    app.kubernetes.io/version: "1.0.0-SNAPSHOT"
  type: "LoadBalancer"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  annotations:
    app.quarkus.io/vcs-url: "https://github.com/Stywar/Quakus-security.git"
    app.quarkus.io/build-timestamp: "2020-07-23 - 05:39:59 +0000"
    app.quarkus.io/commit-id: "6cb7c92981249384cb76f02a668eebd789fc7bc3"
  labels:
    app.kubernetes.io/name: "aforo255-security"
    app.kubernetes.io/version: "1.0.0-SNAPSHOT"
  name: "aforo255-security"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "aforo255-security"
      app.kubernetes.io/version: "1.0.0-SNAPSHOT"
  template:
    metadata:
      annotations:
        app.quarkus.io/vcs-url: "https://github.com/Stywar/Quakus-security.git"
        app.quarkus.io/build-timestamp: "2020-07-23 - 05:39:59 +0000"
        app.quarkus.io/commit-id: "6cb7c92981249384cb76f02a668eebd789fc7bc3"
      labels:
        app.kubernetes.io/name: "aforo255-security"
        app.kubernetes.io/version: "1.0.0-SNAPSHOT"
    spec:
      containers:
      - env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        image: "docker.io/antony0618/aforo255-security:v2.__Build.BuildId__"
        imagePullPolicy: "IfNotPresent"
        name: "aforo255-security"
        ports:
        - containerPort: 8080
          name: "http"
          protocol: "TCP"
      serviceAccount: "aforo255-security"
